name: Publish Crate

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    environment: publish_crate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish to crates.io
        run: cargo publish -v
